cafes/urls.py
from django.urls import path
from . import views

app_name = "cafes"

urlpatterns = [
    path("<int:id>", views.CafeDetail.as_view(), name="viewDetail"),
    path("search/", views.SearchView.as_view(), name="viewSearch"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # 모든 경로를 core에서 처리한다.
    path("", include("core.urls", namespace="core")),
    path("cafes/", include("cafes.urls", namespace="cafes")),
    path('admin/', admin.site.urls),
]

# 개발모드일 경우에만 우리가 지정한 경로로 들어가서 media를 읽어온다.
# 배포일 경우엔 이 방법이 효울적이지 못함
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from cafes import views as CafeViews

app_name = "core"

urlpatterns = [
    path("", CafeViews.HomeView.as_view(), name="CoreHomeView"),
    path("city/<str:county>/", CafeViews.CityDetail.as_view(), name="CityHomeView"),
]

templates/partials/cafe_card.html
{% comment %} <div class="w-1/4 mb-10 px-2">
    <div class="w-full h-64 bg-cover bg-center rounded-lg mb-3" style="background-image: url({{cafe.first_photo}});"></div>
    <div class="flex justify-between">
        <div class="text-gray-600">
            {{cafe.country}}
        </div>
        <span class="text-sm flex items-center">
            <i class="fas fa-star text-red-500 text-xs mr-1"></i> {{cafe.total_rating}}
        </span>
    </div>
    <a href="{% url 'cafes:viewDetail' cafe.pk  %}">
        <span class="text-black w-11/12 block truncate">{{cafe.cafeName}}</span>
    </a>
</div> {% endcomment %}

        <div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">

            <!-- Article -->
            <article class="overflow-hidden rounded-lg shadow-lg">

                <a href="{% url 'cafes:viewDetail' cafe.pk  %}">
                    <img alt="Placeholder" class="block h-80 w-full" src="{{cafe.first_photo}}">
                </a>

                <header class="flex items-center justify-between leading-tight p-2 md:p-4">
                    <h1 class="text-lg">
                        <a class="no-underline hover:underline text-black" href="{% url 'cafes:viewDetail' cafe.pk  %}">
                            {{cafe.cafeName}}
                        </a>
                    </h1>
                    <p class="text-grey-darker text-sm">
                        
                    </p>
                </header>

                <footer class="flex items-center justify-between leading-none p-2 md:p-4">
                    <a class="flex items-center no-underline hover:underline text-black" href="#">
                        <img alt="Placeholder" class="block rounded-full" src="https://picsum.photos/32/32/?random">
                        <p class="ml-2 text-sm">
                            {{cafe.country}}
                        </p>
                    </a>
                    <a class="no-underline text-grey-darker hover:text-red-dark" href="#">
                        <span class="hidden">Like</span>
                        <i class="fas fa-star text-red-500"> </i>{{cafe.total_rating}}
                    </a>
                </footer>

            </article>
        </div>

templates/partials/footer.html
<footer>
    &copy; Nbnb
</footer>

templates/partials/header.html
{% load static %}
    <ul class="flex items-center text-sm font-medium h-full">
        <li class="ml-8 border-b-2 border-white h-full flex items-center hover:border-blue-400"><a href="#">로그인</a></li>
        <li class="ml-8 border-b-2 border-white h-full flex items-center hover:border-blue-400"><a href="#">회원가입</a></li>
    </ul>