cafes/urls.py
from django.urls import path
from . import views

app_name = "cafes"

urlpatterns = [
    path("<int:id>", views.CafeDetail.as_view(), name="viewDetail"),
    path("search/", views.SearchView.as_view(), name="viewSearch"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # 모든 경로를 core에서 처리한다.
    path("", include("core.urls", namespace="core")),
    path("cafes/", include("cafes.urls", namespace="cafes")),
    path('admin/', admin.site.urls),
]

# 개발모드일 경우에만 우리가 지정한 경로로 들어가서 media를 읽어온다.
# 배포일 경우엔 이 방법이 효울적이지 못함
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from cafes import views as CafeViews

app_name = "core"

urlpatterns = [
    path("", CafeViews.HomeView.as_view(), name="CoreHomeView"),
    path("city/<str:county>/", CafeViews.CityDetail.as_view(), name="CityHomeView"),
]

cafes/models.py
from django.db import models
from core import models as CoreModle
from ConsVar import ConstVar
from users import models as userModel
from phonenumber_field.modelfields import PhoneNumberField
from smart_selects.db_fields import ChainedForeignKey

from django.urls import reverse

# 장고에서 HTML상의 코드를 방어하고 있는것을 안전하다고 인식시켜서 HTML코드를 사용하게 해준다.
from django.utils.html import mark_safe

class MenuItem(CoreModle.TimeStampedModel):
    '''
    * 다대다의 메뉴 관리 모델
    '''

    name = models.CharField(max_length=80, null=True, blank=True, verbose_name='메뉴')
    price = models.IntegerField(null=True, blank=True, verbose_name='가격')

    class Meta:
        abstract = True

    def __str__(self):
        return f'{self.name}, {self.price}'

class CafeType(CoreModle.AbstractItem):
    class Meta:
        verbose_name_plural = "카페 종류"

class Menu(MenuItem):
    class Meta:
        verbose_name_plural = "메뉴"


class Country(models.Model):
    name = models.CharField(max_length=30, null=True, blank=True)
    def __str__(self):
        return self.name

class City(models.Model):
    # City = models.CharField(
    #     choices=ConstVar.CITY_CHOICES, max_length=10, null=True, blank=True, verbose_name='시'
    # )
    name = models.CharField(max_length=30, null=True)
    continent = models.ManyToManyField(Country, blank=True, related_name='cafeCity')
    def __str__(self):
        return self.name



class Cafe(CoreModle.TimeStampedModel):
    '''
    * core에서 데이터가 생성되는 날짜와 업데이트되는 날짜를 상속받아서 사용한다.
    '''
    # 카페이름
    cafeName = models.CharField(max_length=30)

    # 설명
    description = models.TextField()


    # city = models.CharField(
    #     choices=ConstVar.CITY_CHOICES, max_length=10, null=True, blank=True, verbose_name='시'
    # )

    # 시
    city = models.CharField(
        choices=ConstVar.CITY_CHOICES, max_length=10, null=True, blank=True, verbose_name='시'
    )

    # 구
    country = models.CharField(
        choices=ConstVar.COUNTRY_CHOICES, max_length=10, null=True, blank=True, verbose_name='구'
    )

    # 동
    district = models.CharField(
        choices=ConstVar.DISTRICT_CHOICES, max_length=10, null=True, blank=True, verbose_name='동'
    )

    # 주소
    address = models.CharField(max_length=150)

    # 카페사이트
    website = models.CharField(max_length=200, null=True, blank=True)
    
    # 카페전화번호
    # cafeNumber = PhoneNumberField(null=True, blank=True)

    # 가게 시작시간
    start = models.TimeField(null=True, blank=True, verbose_name='영업 시작시간')

    # 가게 종료시간
    end = models.TimeField(null=True, blank=True, verbose_name='영업 종료시간')
    
    # 주차장 유/무
    parkSite = models.BooleanField(default=False,null=True, blank=True)
    
    # 가게 주인 
    # FIXME: 어차피 카페를 내가 관리할거면 딱히 필요는 없을것 같음
    # 역참조를 위해서 기존의 _set을 사용하기엔 너무 귀찮으니까 related_name을 사용한다.
    # 정참조는 상관없음
    # 정참조란 현재 Cafe를 바라보고 있는 host는 Cafe모델에서 cafe.host.요소 이런식으로 접근이 가능하다.
    # 반면 user쪽에서는 어떤 카페데이터를 가지고 있는지 알 수 없다.
    # 그렇기 때문에 만들어진게 related_name을 사용해서 역으로 user모델에서도 cafe를 알 수 있도록한다.
    # 즉, 특정 유저가 어떤 카페의 정보를 가지고 있는지 알 수 있게 된다.
    host = models.ForeignKey(userModel.User, on_delete=models.CASCADE, related_name='owner')

    cafetype = models.ForeignKey(CafeType, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='카페 타입', related_name='owner')

    # 카페 종류는 한 카페안에서도 같은 맥락 및 여러 메뉴를 갖을 수 있기 때문에 다대다관계로 사용한다.
    # 커스텀 용이하게 핸들링
    cafeMenu = models.ManyToManyField(Menu, blank=True, related_name='owner')

    def __str__(self):
        return self.cafeName

    # ------------------------------------------------------------------------------------------------------------------
    # override
    # ------------------------------------------------------------------------------------------------------------------
    def save(self, *args, **kwargs):
        '''
        * save를 오버라이드를 통해서 intercepting한다. 
        사용자가 저장하는것을 취향에 맞게 내가 알아서 변경해서 저장
        '''
        # super()를 이용하여 부모클래스에 접근할 수 있도록한다.
        # 현재 따로 수행하는 일이 없어서 주석해도 상관없음 
        # 단 override되고 있기 때문에, 함수 전체를 주석처리 해야함
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # admin 패널에서 해당 페이지로 넘길 수 있겠금, reverse함수를 사용한다.
        # 우리가 만든 viewDetail(cafes/View 함수)은 파라미터를 받아야하기 때문에 우리가 지정한 id와 맞춰서 id를 넘겨준다.
        return reverse('cafes:viewDetail', kwargs={'id':self.id})

    # ------------------------------------------------------------------------------------------------------------------
    # QUREYSET & MANAGE
    # ORM Qureyset 문서
    # https://docs.djangoproject.com/en/3.2/topics/db/queries/
    # 함수에서 obj를 읽어오는 기준은 Row를 기준으로 읽는다.
    # option : all(), count()
    # ------------------------------------------------------------------------------------------------------------------
    def count_cafeMenu(self):
        cafeMenuCount = self.cafeMenu.count()
        return cafeMenuCount

    def count_cafePhoto(self):
        cafePhotoCount = self.cafephotos.count()
        return cafePhotoCount

    def total_rating(self):
        # related_name='reviews' 리뷰 모델의 related키로 받고있기때문에 접근가능
        all_reviews = self.reviews.all()
        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()

        if all_ratings == 0:
            return all_ratings / 1
        else:
            return round(all_ratings / len(all_reviews),2)

    def first_photo(self):
        photo, = self.cafephotos.all()[:1]
        return photo.file.url

    def get_next_four_photos(self):
        photo = self.cafephotos.all()[1:5]
        return photo


class Photo(CoreModle.TimeStampedModel):
    '''
    * 카페 이미지 모델
    '''

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to='cafeImages')

    # 카페가 삭제되면 이미지도 삭제되야하므로, 연결해준다.
    room = models.ForeignKey(Cafe, on_delete=models.CASCADE, related_name='cafephotos')

    def __str__(self):
        return self.caption

    def get_thumbNali(self):
        '''
        * dir()을 통해서 property를 확인해서 필요한 정보를 가져옴
        print(self.file.url)
        print(self.file.size)
        print(self.file.width)
        print(self.file.height)
        '''
        return mark_safe(f'<img width="150px" src="{self.file.url}" />')

cafes/forms.py
from django import forms
from cafes.models import Cafe, CafeType
from ConsVar import ConstVar
# View단에서 처리할 Form의 형식을 만들어줌
class SearchForm(forms.Form):

    # 지역
    city = forms.ChoiceField(required=False, choices=ConstVar.COUNTRY_CHOICES, label='지역')

    # 카페종류
    cafetypes = forms.ModelChoiceField(required=False, queryset=CafeType.objects.all(), label='카페종류')

    # 주차시설
    parking = forms.BooleanField(required=False, label='주차시설')
    
    # 지역마다 표시되는 항목 따르게 처리해야함     

cafes/views.py
from django.shortcuts import render
from cafes.models import Cafe, CafeType, City
from django.views.generic import ListView, DetailView, View
from cafes.forms import SearchForm
from ConsVar.ConstVar import CITY_CHOICES, COUNTRY_CHOICES_GANGNAM, COUNTRY_CHOICES_GANGBOK

class HomeView(ListView):
    '''
    * 함수 사용시 render를 이용
    allCafeData = Cafe.objects.all()
    return render(request, "cafes/cafe_list.html", {'cafes' : allCafeData})
    '''
    model = Cafe
    paginate_by = 12
    paginate_orphans = 5
    ordering = ['created']

    # 기존 Html로 넘어가는 context의 이름을 변경함 object_list -> cafes
    context_object_name = 'cafes'

    def get_context_data(self, **kwargs):
        # 요소 추가로 전달하고 싶을때 사용
        # print(City.continent.objects.all())
        context = super().get_context_data(**kwargs)
        context["cityList"] = City.objects.all()
        return context


    # def get(self, request, id):
    #     print(id)
    #     # return render(request, "cafes/search.html")
    #     pass


class CafeDetail(DetailView):
    model = Cafe
    # 기본적으로 DetailView가 pk로 지정이 되어있기 때문에 내가 커스텀하려면
    # 아래의 옵션 사용해야함.
    pk_url_kwarg = 'id'


class CityDetail(View):
    def get(self, request, county):
        # 조건문
        cafes = Cafe.objects.filter(country=county)
        cityObj = City.objects.all()
        return render(request, "cafes/cafe_list.html", {'cafes' : cafes, 'cityList':cityObj})



class SearchView(View):
    def get(self,request):
        # UI단에서 보내온 요청을 SearchForm 클래스로 넘겨준다.
        form = SearchForm(request.GET)

        if form.is_valid():
            # 클래스 모든 조건식이 들어왔을 경우

            city = form.cleaned_data.get("city")
            cafetypes = form.cleaned_data.get("cafetypes")
            parking = form.cleaned_data.get("parking")

            # 조건문
            filterArgs = {}

            if parking == True:
                filterArgs['parkSite'] = True

            if cafetypes is not None:
                # cafetype은 Cafe 클래스의 foreignKey!
                filterArgs['cafetype'] = cafetypes

            if city is not None:
                filterArgs['country'] = city

            cafes = Cafe.objects.filter(**filterArgs)

            return render(request, 'cafes/search.html', {"form": form, 'cafes': cafes})

        else:

            form = SearchForm()

        return render(request, 'cafes/search.html', {"form": form})
'''
    # ------------------------------------------------------------------------------------------------------------------
    # 함수형으로 View를 만들었을 경우 예시
    # Form API클래스를 사용하여 더 간단하게 표현하기 위해서 Form.py클래스를 생성하고 import해서 사용!
    # ------------------------------------------------------------------------------------------------------------------
def search(request):
    # HTML Tag에서 name으로 검색, 없으면 Default로 '검색결과없음'을 띄움
    # HTML에서 가져온 데이터를 담아두려고 처리함

    # FrontUI
    UIcafetype = int(request.GET.get('cafetype',0))
    UIparking = bool(request.GET.get("inputPark", False))
    GetFromSearchBar = request.GET.get('InputCity', '검색결과없음')
    form = {'city':GetFromSearchBar, 'UIcafetype':UIcafetype, 'UIparking':UIparking}


    # DB에서 온 데이터
    cafetype = CafeType.objects.all()

    choices = {'cafetypes':cafetype }
    # ------------------------------------------------------------------------------------------------------------------
    # View: FrontEnd에서 가져온 데이터를 통해서 DB를 검색해서 필요한 데이터만 화면에 다시 Render
    # 검색조건을 통해서 내가 원하는 방을 띄워준다.
    # ------------------------------------------------------------------------------------------------------------------

    filterArgs = {}

    if UIparking == True:
        filterArgs['parkSite'] = True

    if UIcafetype != 0:
        # cafetype은 Cafe 클래스의 foreignKey!
        filterArgs['cafetype__id'] = UIcafetype

    cafes = Cafe.objects.filter(**filterArgs)

    return render(
        request,
        'cafes/search.html',
        # UI에서 지정한 값을 지워지지않고 Default로 올려두기로 위함
        # '*변수'일 경우는 인자의 갯수가 제한이 없다
        # '**변수'일 경우 딕셔너리형태의 데이터로 보낸다.
        {**form, **choices, 'cafes':cafes}
    )
'''

templates/cafes/cafe_city.html
{% load static %}
<!-- href="{% url 'core:CoreHomeView' %} -->
        <div>
            <img class="w-20" src="{% static 'img/city.jpg' %}" />
                <div class=" relative inline-block text-left dropdown">
                    <button class="inline-flex justify-center w-full px-4 py-2 text-sm font-medium leading-5 text-gray-700 transition duration-150 ease-in-out bg-white border border-gray-300 rounded-md hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800"
                type="button" aria-haspopup="true" aria-expanded="true" aria-controls="headlessui-menu-items-117">
                <span>{{city}}</span>
                    <div class="opacity-0 invisible dropdown-menu transition-all duration-300 transform origin-top-right -translate-y-2 scale-95">
              <div class="absolute right-0 w-56 mt-2 origin-top-right bg-white border border-gray-200 divide-y divide-gray-100 rounded-md shadow-lg outline-none" aria-labelledby="headlessui-menu-button-1" id="headlessui-menu-items-117" role="menu">
                <div class="py-1">
                    {% for county in city.continent.all %}
                        <a href="{% url 'core:CityHomeView' county %}" tabindex="0" class="text-gray-700 flex justify-between w-full px-4 py-2 text-sm leading-5 text-left"  role="menuitem" >{{county}}</a>
                    {% endfor %}
                    </div>
                </div>
              </div>
            </div>
        </div>

templates/cafes/cafe_detail.html
{% extends "base.html" %}

{% block page_name %}
    {{cafe.cafeName}}
{% endblock page_name %}

<!--내용-->
{% block content %}
<div>
        <div class="-mt-5 container max-w-full  flex mb-20">
            <div class="h-screen w-1/2 bg-center bg-cover" style="background-image:url({{cafe.first_photo}});"></div>
        <div class="h-screen w-1/2 flex flex-wrap">
            {% for photo in cafe.get_next_four_photos %}
                <div style="background-image:url({{photo.file.url}})" class="w-1/2 h-auto bg-cover bg-center border-gray-700 border"></div>
            {% endfor %}
        </div>
        </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{cafe.cafeName}}</h4>
                    <span class="text-gray-700 font-light">{{cafe.country}}</span>
                </div>

            </div>
            <div class="flex border-b border-gray-400 pb-8 mt-8">
                <span class="mr-5 font-light">{{cafe.cafetype}}</span>
            </div>
            <p class="border-b border-gray-400 pb-8 mt-8">
                {{cafe.description}}
            </p>

            <div class="border-b border-gray-400 pb-8 mt-8">
                <h4 class="font-medium text-lg mb-5">메뉴</h4>
                {% for a in cafe.cafeMenu.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="mt-8">
                <h4 class="font-medium text-2xl mb-5">후기</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-teal-500"></i>
                        <span class="font-bold text-xl">{{cafe.total_rating}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-5"></div>
                    <span class="font-bold text-xl">{{cafe.reviews.count}}</span>
                    <span>review{{cafe.reviews.count|pluralize}}</span>
                </div>
                <div class="mt-10">
                    {% for a in cafe.reviews.all %}
                        <div class="border-b border-gray-400 pb-8 mt-8">
                            <div class="mb-3 flex">
                                <div class="flex flex-col ml-5">
                                    <span class="font-medium">{{a.user.first_name}}</span>
                                    <span class="text-sm text-gray-500 mt-3">{{a.created|date:'y.m.j'}}</span>
                                </div>
                            </div>
                            <p>{{a.review}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="w-1/3"></div>
    </div> 
{% endblock %}

{% comment %} 
<link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
<link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">

  <section class="relative block h-500-px -mt-5">
    <div class="absolute top-0 w-full h-full bg-center bg-cover" style="background-image: url({{cafe.first_photo}});">
      <span id="blackOverlay" class="w-full h-full absolute opacity-50 bg-black"></span>
    </div>
    <div class="top-auto bottom-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden h-70-px" style="transform: translateZ(0px)">
      <svg class="absolute bottom-0 overflow-hidden" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" version="1.1" viewBox="0 0 2560 100" x="0" y="0">
        <polygon class="text-blueGray-200 fill-current" points="2560 0 2560 100 0 100"></polygon>
      </svg>
    </div>
  </section>
  <section class="relative py-16 bg-blueGray-200">
    <div class="container mx-auto px-4">
      <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64">
        <div class="px-6">
          <div class="flex flex-wrap justify-center">
            <div class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center">
              <div class="relative">
                <img alt="..." src="https://demos.creative-tim.com/notus-js/assets/img/team-2-800x800.jpg" class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16 max-w-150-px">
              </div>
            </div>
            <div class="w-full lg:w-4/12 px-4 lg:order-3 lg:text-right lg:self-center">
              <div class="py-6 px-3 mt-32 sm:mt-0">
                <button class="bg-pink-500 active:bg-pink-600 uppercase text-white font-bold hover:shadow-md shadow text-xs px-4 py-2 rounded outline-none focus:outline-none sm:mr-2 mb-1 ease-linear transition-all duration-150" type="button">
                  Connect
                </button>
              </div>
            </div>
            <div class="w-full lg:w-4/12 px-4 lg:order-1">
              <div class="flex justify-center py-4 lg:pt-4 pt-8">
                <div class="mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">22</span><span class="text-sm text-blueGray-400">Friends</span>
                </div>
                <div class="mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">{{cafe.total_rating}}</span><span class="text-sm text-blueGray-400">별점</span>
                </div>
                <div class="lg:mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">{{cafe.reviews.count}}</span><span class="text-sm text-blueGray-400">리뷰</span>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center mt-12">
            <h3 class="text-4xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2">
              {{cafe.cafeName}}
            </h3>
            <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
              <i class="fas fa-map-marker-alt mr-2 text-lg text-blueGray-400"></i>
              {{cafe.country}}
            </div>
            <div class="mb-2 text-blueGray-600 mt-10">
              <i class="fas fa-briefcase mr-2 text-lg text-blueGray-400"></i>{{cafe.cafetype}}
            </div>
            <div class="mb-2 text-blueGray-600">
              <i class="fas fa-university mr-2 text-lg text-blueGray-400"></i>University of Computer Science
            </div>
          </div>


          <div class="mt-10 py-10 border-t border-blueGray-200 text-center">
            <div class="flex flex-wrap justify-center">
              <div class="w-full lg:w-9/12 px-4">
                {% comment %} <p class="mb-4 text-lg leading-relaxed text-blueGray-700"> {% endcomment %}
                                      {% comment %} {% for a in cafe.cafeMenu.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %} {% endcomment %}
                {% comment %} </p> {% endcomment %}
              {% comment %} </div>
            </div>
          </div>

          <div class="mt-10 py-10 border-t border-blueGray-200 text-center">
            <div class="flex flex-wrap justify-center">
              <div class="w-full lg:w-9/12 px-4">
                <p class="mb-4 text-lg leading-relaxed text-blueGray-700">
                      {{cafe.description}}
                </p>
              </div>
            </div>
          </div>
          <div class="mt-10 py-10 border-t border-blueGray-200 text-center">
            <div class="flex flex-wrap justify-center">
              <div class="w-full lg:w-9/12 px-4">
<div>
        <div class="-mt-5 container max-w-full  flex mb-20">
            <div class="h-screen w-1/2 bg-center bg-cover" style="background-image:url({{cafe.first_photo}});"></div>
        <div class="h-screen w-1/2 flex flex-wrap">
            {% for photo in cafe.get_next_four_photos %}
                <div style="background-image:url({{photo.file.url}})" class="w-1/2 h-auto bg-cover bg-center border-gray-700 border"></div>
            {% endfor %}
        </div>
        </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </section> 
  {% endcomment %} 

templates/cafes/cafe_list.html
<!--베이스 html에서 모든걸 임포트한다.-->
{% extends "base.html" %}
{% load static %}
<!--block은 자식 템플릿을 넣는 방법 block {name}은 내 마음대로-->
{% block page_name %}
    Home
{% endblock page_name %}

<!--내용-->
{% block content %}
<div class="container mx-auto">

    <div class="flex mb-9 -mx-40 justify-center text-center">
        {% for city in cityList  %}
            <!-- 카페 모델이 가지고 있는 city 넘기기   -->
            {% include 'cafes/cafe_city.html' with city=city  %}
        {% endfor %}
    </div>

<div class="container my-12 mx-auto px-4 md:px-12">
    <div class="flex flex-wrap -mx-1 lg:-mx-4">
    {% for cafe in cafes  %}
        <!--  url 태그를 사용하면 /변수/변수 이런식으로 자동으로 주어짐      -->
        <!-- 내가 가고싶은 url 주소를 입력하면 된다. 즉, cafes url에서 namespace로 지정한 경로로 이동하게 됨-->
        <!--  cafe(내가 partials/cafe_card.html로 넘기고 싶은 변수명) = cafe(loop를 통해 넘기는 변수명)      -->
        {% include 'partials/cafe_card.html' with cafe=cafe %}
<!--        <a href="{% url 'cafes:viewDetail' cafe.pk  %}">-->
<!--            <h1>{{cafe.cafeName}}</h1>-->
<!--        </a>-->
<!--        {{cafe.city}} - {{cafe.cafetype}}-->
    {% endfor %}
        </div>
    </div> 
    <div class="flex items-center justify-center mx-auto container">
        <h5>
               {% if page_obj.has_previous %}
                    <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
                        <i class="fas fa-arrow-left fa-lg"></i>
                    </a>
                {% endif %}

                <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

                {% if page_obj.has_next  %}
                    <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
                        <i class="fas fa-arrow-right fa-lg"></i>
                    </a>
                {% endif %}
        </h5>
    </div>
</div>

<style>
.dropdown:focus-within .dropdown-menu {
  opacity:1;
  transform: translate(0) scale(1);
  visibility: visible;
}
    </style>
{% endblock content %}

templates/cafes/search.html
{% extends 'base.html' %}

{% block page_name %}
     검색
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}
<!-- def 형식으로 처리했을 경우 아래와 같은 형식으로 HTML구성, Form class를 사용하면 아래의 방식을 사용하지 않아도 됨-->
<!--    <h2>검색!</h2>-->
<!--      &lt;!&ndash; 액션이 들어오면 cafes의 search함수로 이동시키고 get방식으로 데이터를 사용한다.   &ndash;&gt;-->
<!--      <form method="get" action="{% url 'cafes:viewSearch' %}">-->

<!--          &lt;!&ndash;     도시검색창     &ndash;&gt;-->
<!--          <div>-->
<!--            <label for="city">도시명</label>-->
<!--            <input value="{{city}}" id="city" name="InputCity" placeholder="도시명으로 검색" />-->
<!--        </div>-->

<!--        &lt;!&ndash;     카페종류 DropDown     &ndash;&gt;-->
<!--        <div>-->
<!--            <label for="cafetype">카페종류</label>-->
<!--            <select id="cafetype" name="cafetype" >-->
<!--                <option value="0" {% if UIcafetype == 0 %}selected{% endif %}>카페종류</option>-->
<!--                {% for cafetype in cafetypes  %}-->
<!--                    <option value="{{cafetype.id}}" {% if UIcafetype == cafetype.id %}selected{% endif %}>{{cafetype}}</option>-->
<!--                {% endfor %}-->
<!--            </select>-->
<!--        </div>-->

<!--          &lt;!&ndash;    주차시설     &ndash;&gt;-->
<!--          <div>-->
<!--            <label for="inputPark">주차시설</label>-->
<!--            <input type="checkbox" name="inputPark" id="inputPark" {% if UIparking  %}checked{% endif %} />-->
<!--        </div>-->

<!--          <button>검색</button>-->

<!--      </form>-->

<!--    <h2>검색 결과 {{city}}</h2>-->

<!--    &lt;!&ndash; 카페 결과&ndash;&gt;-->
<!--    {% for cafes in cafes  %}-->
<!--        <h3>{{cafes.cafeName}}</h3>-->
<!--    {% endfor %}-->

<!-- Form 형식으로 처리하였을 경우 -->

    <h2>검색!</h2>

    <form method="get" action="{% url "cafes:viewSearch" %}">
        {{form.as_p}}
        <button>Search</button>
    </form>

    <h3>검색결과</h3>

    {% for cafe in cafes %}
        <h3>{{cafe.cafeName}}</h3>
    {% endfor %}


{% endblock content %}